### PR TITLE
Add go package

### PR DESCRIPTION
**Pull request by tl-marco-tormento**
# truelayer-signing
Go package to produce & verify TrueLayer API requests signatures.

```go
// `Tl-Signature` value to send with the request.
signature, err := tlsigning.SignWithPem(Kid, privateKeyBytes).
    Method("POST").
    Path("/payouts").
    Header("Idempotency-Key", idempotencyKey).
    Body(body).
    Sign()
```

### CODE REVIEW

**Comment by alexheretic** [comment]
@tl-marco-tormento I'm happy to approve this for merging if you're happy. We just need to ensure we can publish this the go-way somehow right?

**Comment by alexheretic** [comment]
Note: Some more scenarios to test: https://github.com/TrueLayer/truelayer-signing/pull/16

**Comment by tl-marco-tormento** [comment]
> @tl-marco-tormento I'm happy to approve this for merging if you're happy. We just need to ensure we can publish this the go-way somehow right?

Yep, I just need to check if the git tag can have a "go-1.0.0" format and then we're good to go.

**Comment by tl-marco-tormento** [comment]
> Note: Some more scenarios to test: #16

This implementation was not affected, since it's very close to the rust one and doesn't use external deps to verify the JWS.
But I have implemented a test to verify the enforcement of the payload detachment.

**Review by alexheretic — APPROVED** [review]

**Pull request merged**
